name: Recent GitHub activity
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          FILTER_EVENTS: "PushEvent,CreateEvent,IssueCommentEvent,IssuesEvent,PullRequestEvent,ReleaseEvent,WatchEvent,ForkEvent"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
